# Generated by Django 2.2.24 on 2024-02-01 15:21

from django.db import migrations


def new_building_or_not(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.all():
        if int(flat.construction_year) >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = [
        migrations.RunPython(new_building_or_not),
    ]
