# Generated by Django 5.0.1 on 2024-02-01 16:02

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_auto_20240201_1848"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.CharField(max_length=200, verbose_name="ФИО владельца"),
                ),
                (
                    "owners_phonenumber",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Номер владельца"
                    ),
                ),
                (
                    "owner_pure_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region="RU",
                        verbose_name="Нормализованный номер владельца",
                    ),
                ),
                (
                    "owners_flats",
                    models.ManyToManyField(
                        db_index=True,
                        null=True,
                        related_name="owners_flats",
                        to="property.flat",
                        verbose_name="Квартиры в собственности",
                    ),
                ),
            ],
        ),
    ]
