# Generated by Django 5.0.1 on 2024-02-01 16:03

from django.db import migrations


def fill_info_in_owners(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    flats = Flat.objects.all()
    Owner = apps.get_model("property", "Owner")
    for flat in flats.iterator():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0009_owner"),
    ]

    operations = [
        migrations.RunPython(fill_info_in_owners),
    ]
