# Generated by Django 5.0.1 on 2024-02-13 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0016_remove_flat_owners_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="owners_phonenumber",
        ),
    ]
