# Generated by Django 5.0.1 on 2024-02-13 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0017_remove_owner_owners_phonenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="owners_flats",
            new_name="flats",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="owner_pure_phone",
            new_name="pure_phone",
        ),
    ]
