# Generated by Django 5.0.1 on 2024-02-20 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0018_rename_owners_flats_owner_flats_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="owner",
            new_name="proprietor",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто жаловался",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="flat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flats",
                to="property.flat",
                verbose_name="Квартира, на которую жаловались",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                db_index=True,
                null=True,
                related_name="apartments",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
