# Generated by Django 5.0.1 on 2024-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0019_rename_owner_owner_proprietor_alter_complaint_author_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="flat",
            old_name="owner_pure_phone",
            new_name="pure_phone",
        ),
        migrations.RenameField(
            model_name="owner",
            old_name="proprietor",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="owner",
            name="flats",
            field=models.ManyToManyField(
                db_index=True,
                null=True,
                related_name="owners",
                to="property.flat",
                verbose_name="Квартиры в собственности",
            ),
        ),
    ]
