# Generated by Django 5.0.1 on 2024-02-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0020_rename_owner_pure_phone_flat_pure_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="owner",
        ),
        migrations.AlterField(
            model_name="complaint",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто жаловался",
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="flat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="property.flat",
                verbose_name="Квартира, на которую жаловались",
            ),
        ),
    ]
